blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import UserPostListView, UserPostCreateView, UserPostDetailView, UserPostUpdateView, UserPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', UserPostListView.as_view(), name='blogview'),
    path('create/', UserPostCreateView.as_view(), name='create_post'),
    path('view/<int:pk>/', UserPostDetailView.as_view(), name='view_post'),
    path('edit/<int:pk>/', UserPostUpdateView.as_view(), name='update_post'),
    path('delete/<int:pk>/', UserPostDeleteView.as_view(), name='delete_post')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, user_authentication, RestorePassword, UserExit

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', UserExit.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('user_authentication', user_authentication, name='user_authentication'),
    path('restore_password/', RestorePassword.as_view(), name='restore_password'),
    # path('verification/<str:secret_cod>/', VerificationView.as_view(), name='verification'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="Почта")

    phone = models.CharField(max_length=30, verbose_name="Номер телефона", blank=True, null=True)
    avatar = models.ImageField(upload_to='users/', verbose_name="Аватар", blank=True, null=True)
    country = models.CharField(max_length=25, verbose_name="Страна", blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

users/views.py
import random

from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from config import settings
from users.forms import UserRegisterForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'register.html'

    def form_valid(self, form):
        if form.is_valid():
            user = form.save()

            send_mail(
                "Регистрация нового пользователя",
                f"Успешная регистрация на сайте",
                settings.EMAIL_HOST_USER,
                [user.email]
            )
        return redirect('catalog:products')

    def get_success_url(self):
        return reverse_lazy('users:login')


class RestorePassword(TemplateView):
    template_name = 'restore_password.html'

    def post(self, request, **kwargs):
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        new_password = ""
        if user:
            for i in range(8):
                symbol = random.randint(0, 9)
                new_password += str(symbol)

            send_mail(
                "new_password",
                f'Новый пароль : {new_password}',
                settings.EMAIL_HOST_USER,
                [email]
            )

            user.password = make_password(new_password)
            user.save()
        return redirect('users:login')


class UserExit(TemplateView):
    template_name = 'logged_out.html'

    def post(self, request):
        request.session.delete()
        return redirect('catalog:Home')


def user_authentication(request):
    return render(request, 'user_authentication.html')

users/templates/logged_out.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3 class="text mb-3">Вы уверены??</h3>
    <button type="submit" class="btn btn-primary">Да</button>
</form>
{% endblock %}

users/templates/login.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
    {{ form.as_p }}

    <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Войти</button>
    </div>
</form>
{% endblock %}

users/templates/register.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
    {{ form.as_p }}

    <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Регистрация</button>
        <a type="submit" class="btn btn-primary mb-3" href="{% url 'users:restore_password' %}">Восстановить пароль</a>
    </div>
</form>
{% endblock %}

users/templates/restore_password.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
    <h4 class="text">Введите почту: </h4>
    <input class="email mb-5" name="email">

    <div class="col-auto">

        <button type="submit" class="btn btn-primary">Отправить на почту</button>
    </div>
</form>
{% endblock %}

users/templates/user_authentication.html
{% extends 'base.html' %}

{% block content %}
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <h2 class="text">Для продолжения проверьте почту</h2>
            </div>
        </div>
    </div>
{% endblock %}