blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import UserPostListView, UserPostCreateView, UserPostDetailView, UserPostUpdateView, UserPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', UserPostListView.as_view(), name='blogview'),
    path('create/', UserPostCreateView.as_view(), name='create_post'),
    path('view/<int:pk>/', UserPostDetailView.as_view(), name='view_post'),
    path('edit/<int:pk>/', UserPostUpdateView.as_view(), name='update_post'),
    path('delete/<int:pk>/', UserPostDeleteView.as_view(), name='delete_post')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime


class UserPost(models.Model):
    title = models.CharField(max_length=150, verbose_name="Заголовок")
    slug = models.CharField(max_length=150, verbose_name="slug", blank=True, null=True)
    content = models.TextField(verbose_name="Содержимое")
    picture = models.ImageField(upload_to="blog_picture/", verbose_name="Картинка", blank=True, null=True)
    creation_date = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    publication_sign = models.BooleanField(default=False, verbose_name="Знак публикации")
    views_count = models.IntegerField(default=0, verbose_name="Просмотры")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Blog"

blog/views.py
from django.urls import reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import UserPost


class UserPostListView(ListView):
    model = UserPost

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication_sign=True)
        return queryset

    def get_context_data(self, **kwargs):
        """ Получение контекста """
        context = super().get_context_data(**kwargs)
        context["title"] = "Блог"
        return context


class UserPostCreateView(CreateView):
    model = UserPost
    fields = ('title', 'content', 'picture', 'publication_sign')
    success_url = '/blog'

    def form_valid(self, form):
        if form.is_valid():
            new_userpost = form.save()
            new_userpost.slug = slugify(new_userpost.title)
            new_userpost.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """ Получение данных контекста """
        context = super().get_context_data(**kwargs)
        context["title"] = "Новая запись"
        return context


class UserPostDetailView(DetailView):
    model = UserPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class UserPostUpdateView(UpdateView):
    model = UserPost
    fields = ('title', 'content', 'picture', 'publication_sign')

    def form_valid(self, form):
        if form.is_valid():
            new_userpost = form.save()
            new_userpost.slug = slugify(new_userpost.title)
            new_userpost.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view_post', args=[self.kwargs.get("pk")])


class UserPostDeleteView(DeleteView):
    model = UserPost
    success_url = '/blog'

blog/templates/blog/userpost_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
    <p> Удалить {{ object.title }} ???</p>

    <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Подтвердить</button>
    </div>
</form>
{% endblock %}

blog/templates/blog/userpost_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="card" style="width: 18rem;">
  <img src="{{ object.image }}" class="card-img-top" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{ object.title }}</h5>
    <p class="card-text">{{ object.content }}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Дата создания: {{ object.creation_date }}</li>
    <li class="list-group-item">slug: {{ object.slug }}</li>
    <li class="list-group-item">Знак публикации: {{ object.publication_sign }}</li>
    <li class="list-group-item">Просмотры: {{ object.views_count }}</li>
  </ul>
  <div class="card-body">
    <a href="{% url 'blog:update_post' object.pk %}" class="card-link">Редактировать</a>
    <a href="{% url 'blog:delete_post' object.pk %}" class="card-link">Удалить</a>
  </div>
</div>
{% endblock %}

blog/templates/blog/userpost_form.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
    {{ form.as_p }}

    <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Сохранить</button>
    </div>
</form>
{% endblock %}

blog/templates/blog/userpost_list.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="create/">Новая запись</a>
    </nav>
</div>

<div class="row">
  {% for object in object_list %}
  <div class="col-md-4">
    <div class="card mb-4 box-shadow">
      <img class="card-img-top" src="{{ object.image }}" alt="Card image cap">
      <div class="card-body">
        <p class="card-text">{{object}}</p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'blog:view_post' object.pk %}">Просмотр</a>
            <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'blog:update_post' object.pk %}">Редактирование</a>
            <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'blog:delete_post' object.pk %}">Удаление</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}