blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import UserPostListView, UserPostCreateView, UserPostDetailView, UserPostUpdateView, UserPostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', UserPostListView.as_view(), name='blogview'),
    path('create/', UserPostCreateView.as_view(), name='create_post'),
    path('view/<int:pk>/', UserPostDetailView.as_view(), name='view_post'),
    path('edit/<int:pk>/', UserPostUpdateView.as_view(), name='update_post'),
    path('delete/<int:pk>/', UserPostDeleteView.as_view(), name='delete_post')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (ProductListView,
                           HomeView,
                           ContactsView,
                           ProductCreateView,
                           ProductDetailView,
                           ProductUpdateView,
                           ProductDeleteView, CategoryListView)


app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='Home'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('list/', ProductListView.as_view(), name='products'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('detail/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование категории")
    description = models.TextField(verbose_name="Описание категории")

    def __str__(self):
        return f"{self.name} {self.description}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100, verbose_name="Наименование продукта")
    description = models.TextField(verbose_name="Описание")
    image = models.ImageField(upload_to="products_photo", verbose_name="Изображение", blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True, related_name="Products")
    price = models.IntegerField(verbose_name="Цена")
    is_published = models.BooleanField(default=False, verbose_name="Признак публикации")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateField(auto_now=True, verbose_name="Дата изменения")

    def __str__(self):
        return f"{self.name} {self.price} {self.description}"

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        permissions = [
            ("can_change_publication", "can_change_publication"),
            ("can_change_description", "can_change_description"),
            ("can_change_category", "can_change_category")
        ]


class Version(models.Model):
    name = models.CharField(max_length=150, verbose_name="Название версии")
    number = models.CharField(max_length=10, verbose_name="Номер версии")
    current = models.BooleanField(verbose_name="Признак текущей версии")

    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.number}"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')


class ProductForm(StyleFormMixin, forms.ModelForm):
    ban_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('name', 'description', 'image', 'price', 'category', "is_published")

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        for word in self.ban_words:
            if word in cleaned_data.split():
                raise forms.ValidationError('Недопустимое слово в имени')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        for word in self.ban_words:
            if word in cleaned_data.split():
                raise forms.ValidationError('Недопустимое слово в описании')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = ('name', 'number', 'current')

catalog/views.py
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version, Category
from catalog.services import get_categories


class HomeView(TemplateView):
    """
    Просмотр домашней страницы
    """
    template_name = "catalog/home.html"

    def get_context_data(self, **kwargs):
        """ Получение контекста """
        context = super().get_context_data(**kwargs)
        context["title"] = "Skystore"
        return context


class ContactsView(TemplateView):
    """ Просмотр страницы контактов """
    template_name = "catalog/contacts.html"

    def post(self, request, **kwargs):
        """ Обработка POST запроса"""
        context = self.get_context_data(**kwargs)
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(name, phone, message)

        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        """ Получение данных контекста """
        context = super().get_context_data(**kwargs)
        context["title"] = "Контакты"
        return context


class ProductListView(LoginRequiredMixin, ListView):
    """
    Просмотр страницы продуктов
    """
    model = Product
    login_url = "/users"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        """ Получение данных контекста"""
        context = super().get_context_data(**kwargs)
        context["title"] = "Продукты"
        for product in self.object_list:
            version = Version.objects.get(product=product.pk, current=True).number
            if version:
                product.version = version
            else:
                product.version = "null"
        return context


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == "POST":
            context["formset"] = VersionFormset(self.request.POST)
        else:
            context["formset"] = VersionFormset()
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        self.object.user = self.request.user
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_id = self.kwargs.get('pk')
        version = Version.objects.get(product=product_id, current=True)
        context["title"] = Product.objects.get(id=product_id).name
        if version:
            context["version"] = version
        else:
            context["version"] = "null"
        return context

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        user = self.request.user
        if user.groups.filter(name="moderators").exists():
            obj.prems = True
        else:
            obj.prems = False
        return obj


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == "POST":
            context["formset"] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context["formset"] = VersionFormset(instance=self.object)
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return ProductForm
        if user.groups.filter(name="moderators").exists():
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products')


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    login_url = "/users"
    redirect_field_name = "redirect_to"

    def get_queryset(self):
        return get_categories()

catalog/templates/catalog/category_list.html
{% extends 'base.html' %}
{% load static %}
{% load my_filter %}
{% block content %}

<div class="row">
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
                <p class="card-text">{{object.description}}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'base.html' %}

{% block content %}
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Введите сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1 class="text">Подтвердите удаление</h1>
    <button type="submit" class="btn btn-primary">Подтвердить</button>
</form>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h5 class="card-text">{{ object.description }}</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Версия: {{ version.number }}</li>
        <li class="list-group-item">Цена: {{ object.price }}</li>
        <li class="list-group-item">Категория: {{ object.category }}</li>
        <li class="list-group-item">Дата создания: {{ object.created_at }}</li>
    </ul>
    <div class="card-body">
        {% if user == object.user or object.prems %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:update_product' object.pk %}">Редактировать</a>
        {% endif %}
        {% if user == object.user %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:delete_product' object.pk %}">Удалить</a>
        {% endif %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form.as_p }}
                {% if not forloop.last %}
                    <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'base.html' %}
{% load static %}
{% load my_filter %}
{% block content %}

<div class="row">
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{{ object.image | mod_path }}" alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
                <p class="card-text">Version: {{object.version}}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:view_product' object.pk %}">Просмотр</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}